version: "2"
services:

  aria2:
    image: hobbsau/aria2 
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}/aria2:/home/aria2
    network_mode: host

  transmission:
    image: linuxserver/transmission
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${STORAGE_DIR}:/downloads
    environment:
      - PUID=${UID}
      - PGID=${GID}
    network_mode: host

  cms:
    image: lixiaocong/lxccms
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}:/storage
      - ${CONFIG_DIR}:/config
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - APPLICATION_URL=${APPLICATION_URL}
      - QQ_ID=${QQ_ID}
      - QQ_SECRET=${QQ_SECRET}
      - WEIXIN_ID=${WEIXIN_ID}
      - WEIXIN_SECRET=${WEIXIN_SECRET}
      - WEIXIN_TOKEN=${WEIXIN_TOKEN}
      - WEIXIN_KEY=${WEIXIN_KEY}
    network_mode: host

  nginx:
    image: nginx:1.13
    user: "${UID}"
    volumes:
      - ${CONFIG_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${STORAGE_DIR}:/storage
    network_mode: host

  shadowsocks:
    image: easypi/shadowsocks-libev
    user: "${UID}"
    environment:
      - METHOD=${SS_METHOD}
      - PASSWORD=${SS_PASSWD}
    network_mode: host
