version: "2"
services:
  cms:
    build: ..
    user: ${UID}
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.13
    user: ${UID}
    volumes:
      - ${CONFIG_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CONFIG_DIR}/nginx/html:/html
      - ${STORAGE_DIR}:/storage
    links:
      - cms
    ports:
      - 80:80

  aria2:
    image: hobbsau/aria2 
    user: ${UID}
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}/aria2:/home/aria2
    expose:
      - 6800
    ports:
      - 6800:6800

  transmission:
    image: linuxserver/transmission
    volumes:
      - ${CONFIG_DIR}/transmission/settings.json:/config/settings.json
      - ${STORAGE_DIR}:/downloads
    environment:
      - PUID=${UID}
      - PGID=${GID}
    expose:
      - 9091
    ports:
      - 9091:9091

  shadowsocks:
    image: easypi/shadowsocks-libev
    user: ${UID}
    network_mode: host
    environment:
      - METHOD=${SS_METHOD}
      - PASSWORD=${SS_PASSWD}
