version: "2"
services:
  tomcat:
    image: tomcat:8.5
    expose:
      - 8080

  nginx:
    image: nginx:1.13
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/html:/html
      - ./storage:/storage
    links:
      - tomcat
    ports:
      - 80:80

  aria2:
    image: vimagick/aria2
    volumes:
      - ./config/aria2:/etc/aria2
      - ./storage:/downloads
    environment:
      - TOKEN=password
    network_mode: host

  transmission:
    image: linuxserver/transmission
    volumes:
      - ./config/transmission:/config
      - ./storage:/downloads
    network_mode: host

  shadowsocks:
    image: easypi/shadowsocks-libev
    network_mode: host
    environment:
      - METHOD=aes-256-cfb
      - PASSWORD=password
